# Generated by Django 4.0.2 on 2022-03-31 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='photos/products')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('brand_logo', models.ImageField(null=True, upload_to='photos/brand')),
                ('product_brand', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=40)),
                ('processor', models.CharField(blank=True, max_length=250)),
                ('processor_technology', models.CharField(blank=True, max_length=250)),
                ('graphics', models.CharField(blank=True, max_length=250)),
                ('memory', models.CharField(blank=True, max_length=250)),
                ('hard_drive', models.CharField(blank=True, max_length=250)),
                ('wireless', models.CharField(blank=True, max_length=250)),
                ('power_supply', models.CharField(blank=True, max_length=250)),
                ('battery', models.CharField(blank=True, max_length=250)),
                ('color', models.CharField(blank=True, max_length=250)),
                ('storage', models.CharField(blank=True, max_length=250)),
                ('screen', models.CharField(blank=True, max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text_comment', models.TextField(blank=True)),
                ('date_entry', models.DateTimeField(auto_now_add=True)),
                ('reply_product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('writer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
