# Generated by Django 4.0.3 on 2022-04-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_address_order_item'),
        ('cart', '0002_remove_cartitem_cart_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
