# Generated by Django 4.0.2 on 2022-03-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('order', '0002_delete_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(to='cart.CartItem'),
        ),
    ]
