# Generated by Django 4.0.3 on 2022-04-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_orders_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='address_user',
        ),
    ]
