# Generated by Django 4.0.3 on 2022-04-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_address_address_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='order_item',
        ),
    ]
